#!/usr/bin/python3
import os
import sys


import commonCDN


if __name__ == '__main__':
    args = commonCDN.parse_args(sys.argv)

    os.system('python3 requestcache.py -i torequest.csv -o requested.json')

    os.system('scp -i {} dnsserver {}@cs5700cdnproject.ccs.neu.edu:~'.format(args.i, args.u))
    os.system('ssh -i {} {}@cs5700cdnproject.ccs.neu.edu chmod +x dnsserver'.format(args.i, args.u))

    for rep in commonCDN.replicalist:
        os.system('scp -i {} httpserver cache.py fileifc.py requested.json {}@{}:~'.format(args.i, args.u, rep))
        os.system('ssh -i {} {}@{} chmod +x httpserver'.format(args.i, args.u, rep))
