#!/bin/bash

replicas=(ec2-34-238-192-84.compute-1.amazonaws.com
ec2-13-231-206-182.ap-northeast-1.compute.amazonaws.com
ec2-13-239-22-118.ap-southeast-2.compute.amazonaws.com
ec2-34-248-209-79.eu-west-1.compute.amazonaws.com
ec2-18-231-122-62.sa-east-1.compute.amazonaws.com
ec2-3-101-37-125.us-west-1.compute.amazonaws.com)

# Parsing Input
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -i)
    SSHKEY="$2"
    shift # past argument
    shift # past value
    ;;
    -u)
    USRNAME="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done

# # Cache Prefetch
# # We dont do this part cause we don't know the deployment server has python or not.
# echo Prefetching Cache...
# python3 requestcache.py -i torequest.csv -o requested.json

# Deploying DNS
echo Deploying DNS...
scp -i $SSHKEY dnsserver $USRNAME@cs5700cdnproject.ccs.neu.edu:~
ssh -i $SSHKEY $USRNAME@cs5700cdnproject.ccs.neu.edu chmod +x dnsserver

# Deploying Replicas
for repl in ${replicas[@]}; do
    echo Deploying Replica: $repl
    scp -i $SSHKEY httpserver cache.py fileifc.py requested.json $USRNAME@$repl:~
    ssh -i $SSHKEY $USRNAME@$repl chmod +x httpserver
done

echo Deployment Finished!
