#!/bin/bash

replicas=(ec2-34-238-192-84.compute-1.amazonaws.com
ec2-13-231-206-182.ap-northeast-1.compute.amazonaws.com
ec2-13-239-22-118.ap-southeast-2.compute.amazonaws.com
ec2-34-248-209-79.eu-west-1.compute.amazonaws.com
ec2-18-231-122-62.sa-east-1.compute.amazonaws.com
ec2-3-101-37-125.us-west-1.compute.amazonaws.com)

# Parsing Input
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -i)
    SSHKEY="$2"
    shift # past argument
    shift # past value
    ;;
    -u)
    USRNAME="$2"
    shift # past argument
    shift # past value
    ;;
    -n)
    NME="$2"
    shift # past argument
    shift # past value
    ;;
    -p)
    PRT="$2"
    shift # past argument
    shift # past value
    ;;        
    -o)
    ORIG="$2"
    shift # past argument
    shift # past value
    ;;    
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done


# Run DNS
echo Running DNS
ssh -i $SSHKEY $USRNAME@cs5700cdnproject.ccs.neu.edu "nohup ./dnsserver -p $PRT -n $NME > /dev/null 2>&1 & echo \$! > pid.txt"

# Running Replicas
for repl in ${replicas[@]}; do
    echo Running Replica: $repl
    ssh -i $SSHKEY $USRNAME@$repl "nohup ./httpserver -p $PRT -o $ORIG > /dev/null 2>&1 & echo \$! > pid.txt"
done

echo Ran Everything!
