#!/usr/bin/python3
import os
import sys

import commonCDN
from commonCDN import PIDFILE

if __name__ == '__main__':
    args = commonCDN.parse_args(sys.argv)

    for rep in commonCDN.replicalist:
        os.system('ssh -i {} {}@{} `nohup ./httpserver -p {} -o {} &; echo $! > {}}`'.format(args.i, args.u, rep, args.p, args.o, PIDFILE))
