#!/bin/bash

replicas=(ec2-34-238-192-84.compute-1.amazonaws.com
ec2-13-231-206-182.ap-northeast-1.compute.amazonaws.com
ec2-13-239-22-118.ap-southeast-2.compute.amazonaws.com
ec2-34-248-209-79.eu-west-1.compute.amazonaws.com
ec2-18-231-122-62.sa-east-1.compute.amazonaws.com
ec2-3-101-37-125.us-west-1.compute.amazonaws.com)

# Parsing Input
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -i)
    SSHKEY="$2"
    shift # past argument
    shift # past value
    ;;
    -u)
    USRNAME="$2"
    shift # past argument
    shift # past value
    ;;  
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done


# Stopping DNS
echo Stopping DNS
ssh -i $SSHKEY $USRNAME@cs5700cdnproject.ccs.neu.edu "kill -9 \`cat pid.txt\`"

# Stopping Replicas
for repl in ${replicas[@]}; do
    echo Stopping Replica: $repl
    ssh -i $SSHKEY $USRNAME@$repl "kill -9 `cat pid.txt`"
done

echo Stopped Everything!